---
- name: Install gunicorn
  become: true
  become_user: "{{ app_user }}"
  ansible.builtin.pip:
    name: gunicorn
    virtualenv: "{{ app_basepath }}/venv"
    virtualenv_command: python3.9 -m venv

- name: Copying service-template to server
  become: true
  ansible.builtin.template:
    src: "{{ app_service_file }}"
    dest: /etc/systemd/system/{{ app_name }}.service
    mode: preserve

- name: Start service {{ app_name }}
  become: true
  ansible.builtin.systemd:
    name: "{{ app_name }}.service"
    state: restarted
    daemon_reload: true
    enabled: "{{ app_autostart }}"
